apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
  - port: http
    path: /q/metrics
    interval: 30s